<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class tellmeController extends Controller
{
    public function index(){
        return view('tellme');
    }

    public function Consultation(){
        return view('form');
    }

    public function SoshinaAnswer(Request $request){
        $contents = $request->input("textarea");
        $tweets = array(
            0 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">「なんか悪い事した気分になる、ジャグラーのメダル払い戻し音」 <a href="https://t.co/rB17964XzG">pic.twitter.com/rB17964XzG</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1072488792026726403?ref_src=twsrc%5Etfw">December 11, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            1 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">エ゛エーイ！</p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1254405935386091526?ref_src=twsrc%5Etfw">April 26, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            2 => 'https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fsoshina3%2Fstatus%2F1253708283270979589&widget=Tweet',
            3 => 'https://twitter.com/soshina3/status/1249328318408560640',
            4 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">ドリームマッチ</p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1248868279768076290?ref_src=twsrc%5Etfw">April 11, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            5 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">トム・ブラウンみちおさん(<a href="https://twitter.com/tom_mitio?ref_src=twsrc%5Etfw">@tom_mitio</a>)から回って来ました<br><br>次は学天即の奥田さん(<a href="https://twitter.com/gakutenokuda?ref_src=twsrc%5Etfw">@gakutenokuda</a>)よろしくお願いします！<a href="https://twitter.com/hashtag/%E3%83%AA%E3%83%AC%E3%83%BC%E5%9B%9E%E3%81%A3%E3%81%A6%E3%81%93%E3%81%AA%E3%81%84%E8%8A%B8%E4%BA%BA?src=hash&amp;ref_src=twsrc%5Etfw">#リレー回ってこない芸人</a><a href="https://twitter.com/hashtag/%E3%83%AA%E3%83%AC%E3%83%BC%E3%81%BE%E3%82%8F%E3%81%A3%E3%81%A6%E3%81%93%E3%81%AA%E3%81%84%E3%83%AA%E3%83%AC%E3%83%BC?src=hash&amp;ref_src=twsrc%5Etfw">#リレーまわってこないリレー</a> <a href="https://twitter.com/hashtag/%E3%81%B5%E3%81%96%E3%81%91%E3%82%93%E3%81%AA%E3%82%B3%E3%83%AD%E3%83%8A?src=hash&amp;ref_src=twsrc%5Etfw">#ふざけんなコロナ</a> <a href="https://t.co/t8kcuFpwap">pic.twitter.com/t8kcuFpwap</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1248545271429992453?ref_src=twsrc%5Etfw">April 10, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            6 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">私、メガニウムの声をやらせて頂きます！！ <a href="https://t.co/jnkGoutOS2">https://t.co/jnkGoutOS2</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1245893954660257793?ref_src=twsrc%5Etfw">April 3, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            7 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">私はもうビビらない <a href="https://t.co/axYrSEPJYc">https://t.co/axYrSEPJYc</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1240880334167629824?ref_src=twsrc%5Etfw">March 20, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            8 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">霜降り明星のオールナイトニッポン0<br>継続！<a href="https://twitter.com/hashtag/%E9%9C%9C%E9%99%8D%E3%82%8A%E6%98%8E%E6%98%9FANN0?src=hash&amp;ref_src=twsrc%5Etfw">#霜降り明星ANN0</a> <a href="https://t.co/XaT3ezKr2u">pic.twitter.com/XaT3ezKr2u</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1236880805655281664?ref_src=twsrc%5Etfw">March 9, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            9 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">そういえば明日めざましジャンケン出ます<br>これ出したらすみません <a href="https://t.co/xWdqMvBZUT">pic.twitter.com/xWdqMvBZUT</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1223947583363506181?ref_src=twsrc%5Etfw">February 2, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            10 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">話聞いてるが最初から否定する気しかない人<a href="https://twitter.com/hashtag/%E3%83%AF%E3%83%B3%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%A2%E3%83%8E%E3%83%9E%E3%83%8D?src=hash&amp;ref_src=twsrc%5Etfw">#ワンコインモノマネ</a><a href="https://twitter.com/hashtag/100%E5%86%86%E3%81%90%E3%82%89%E3%81%84%E3%81%AE%E3%83%A2%E3%83%8E%E3%83%9E%E3%83%8D?src=hash&amp;ref_src=twsrc%5Etfw">#100円ぐらいのモノマネ</a> <a href="https://t.co/o1z7BoShBo">pic.twitter.com/o1z7BoShBo</a></p>&mdash; 霜降り明星 せいや (@simofuriseiyam) <a href="https://twitter.com/simofuriseiyam/status/1223214965793755136?ref_src=twsrc%5Etfw">January 31, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            11 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">LINEで粗品のツッコミをする時は<br>このスタンプがオススメです <a href="https://t.co/PGzU25L6mk">pic.twitter.com/PGzU25L6mk</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1107641408297394176?ref_src=twsrc%5Etfw">March 18, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            12 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">扉から良い匂いしてた <a href="https://t.co/B1MqGBv2MT">pic.twitter.com/B1MqGBv2MT</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1222065297407897604?ref_src=twsrc%5Etfw">January 28, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            13 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">東方キャノンボール始めました<a href="https://twitter.com/hashtag/%E6%9D%B1%E6%96%B9%E3%82%AD%E3%83%A3%E3%83%8E%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB?src=hash&amp;ref_src=twsrc%5Etfw">#東方キャノンボール</a> <a href="https://t.co/iqkRHmegzy">pic.twitter.com/iqkRHmegzy</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1201713343309811712?ref_src=twsrc%5Etfw">December 3, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            14 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">ミニオンぼえのない話 <a href="https://t.co/hQtLpjkBf9">pic.twitter.com/hQtLpjkBf9</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1011610201626034176?ref_src=twsrc%5Etfw">June 26, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            15 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">アジの開き直り <a href="https://t.co/DNk3KSvQJh">pic.twitter.com/DNk3KSvQJh</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1002547651542376448?ref_src=twsrc%5Etfw">June 1, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            16 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">小栗旬さんのお父様とお兄様にお会い出来ました<a href="https://twitter.com/hashtag/%E3%82%B5%E3%83%B3%E3%83%88%E3%83%AA%E3%83%BC1%E4%B8%87%E4%BA%BA%E3%81%AE%E7%AC%AC%E4%B9%9D?src=hash&amp;ref_src=twsrc%5Etfw">#サントリー1万人の第九</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1201015113202823168?ref_src=twsrc%5Etfw">December 1, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            17 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">ポケモンは最高やなぁ<br>小さいぬいぐるみを買いました <a href="https://t.co/7xyWSPUMhi">pic.twitter.com/7xyWSPUMhi</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1198960529328365574?ref_src=twsrc%5Etfw">November 25, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            18 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">逃げまーす！ <a href="https://t.co/RIjmctfQbP">https://t.co/RIjmctfQbP</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1195666157614665728?ref_src=twsrc%5Etfw">November 16, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            19 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">やっとレジェンド行きました<br>一通り色々試した結果<br>無色麒麟が強かったです<a href="https://twitter.com/hashtag/%E3%82%BC%E3%83%8E%E3%83%B3%E3%82%B6%E3%83%BC%E3%83%89?src=hash&amp;ref_src=twsrc%5Etfw">#ゼノンザード</a> <a href="https://t.co/vqpC9D5CzG">pic.twitter.com/vqpC9D5CzG</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1189841566472404992?ref_src=twsrc%5Etfw">October 31, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            20 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">「粗品 包装」で検索すると<br>僕の包茎のページが山ほど出てくるん、おかしいと思います <a href="https://t.co/oP8Jm3kDRt">pic.twitter.com/oP8Jm3kDRt</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1159782725798129667?ref_src=twsrc%5Etfw">August 9, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            21 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">インスタやってます<a href="https://t.co/dCkUJi3W37">https://t.co/dCkUJi3W37</a> <a href="https://t.co/5UM0sjTzSq">pic.twitter.com/5UM0sjTzSq</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1152771741606825985?ref_src=twsrc%5Etfw">July 21, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            22 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">ピアノで有名な静岡のトイレの音姫<br><br>優雅やけどピアニッシモのとこ困る <a href="https://t.co/jw39ua0HnD">pic.twitter.com/jw39ua0HnD</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1149141708996632576?ref_src=twsrc%5Etfw">July 11, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            23 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">そんな事よりレムのためにもレムのエモートナーフしてあげて <a href="https://t.co/v1GFVuY2AJ">https://t.co/v1GFVuY2AJ</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1148798199546576896?ref_src=twsrc%5Etfw">July 10, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            24 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">レとラを無くしました <a href="https://t.co/rMlp7Fa3Hs">pic.twitter.com/rMlp7Fa3Hs</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1146796598631919617?ref_src=twsrc%5Etfw">July 4, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            25 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">あんたの口噛み酒ボトルで飲むわ！ <a href="https://t.co/kpXDyaLkr1">https://t.co/kpXDyaLkr1</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1145329934937681920?ref_src=twsrc%5Etfw">June 30, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            26 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">訳がわからん <a href="https://t.co/LrsbUQwyq3">https://t.co/LrsbUQwyq3</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1145212253592903681?ref_src=twsrc%5Etfw">June 30, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            27 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">当たり付きの自動販売機「6666」で当たった<br>時短やから１本しか出てこんかった</p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1138462072621154310?ref_src=twsrc%5Etfw">June 11, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            28 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">サタン耐え切った時の写真置いときます<br>よろしくお願いします<a href="https://twitter.com/hashtag/RAGE%E3%82%B7%E3%83%A3%E3%83%89%E3%82%A6%E3%83%90%E3%83%BC%E3%82%B9?src=hash&amp;ref_src=twsrc%5Etfw">#RAGEシャドウバース</a> <a href="https://t.co/1OwYWVaFyS">pic.twitter.com/1OwYWVaFyS</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1132959898940002304?ref_src=twsrc%5Etfw">May 27, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            29 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">居酒屋で隣に座ってるカップルの女性が凄い剣幕で<br>「この前恐竜みたいな顔の女とホテル行ったでしょ！私の友達が見たって言ってんの！恐竜みたいな顔の女！あれ誰よ！」<br><br>ジュラ場</p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1124647495265468417?ref_src=twsrc%5Etfw">May 4, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            30 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">R-1優勝しました<br>そんな僕より間違いなく面白いのが、せいやです<br>霜降り明星をよろしくお願いします</p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1104757002570366978?ref_src=twsrc%5Etfw">March 10, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            31 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">ケンタイキーフライドチキン <a href="https://t.co/Pbj3yHcIUc">pic.twitter.com/Pbj3yHcIUc</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1104368677657300992?ref_src=twsrc%5Etfw">March 9, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            32 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">インスタやってます<a href="https://t.co/dCkUJi3W37">https://t.co/dCkUJi3W37</a> <a href="https://t.co/34VqFvxGsc">pic.twitter.com/34VqFvxGsc</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1093882243515174912?ref_src=twsrc%5Etfw">February 8, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            33 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">私はここにいる <a href="https://t.co/lKXzSLJyJE">https://t.co/lKXzSLJyJE</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1092609355550097409?ref_src=twsrc%5Etfw">February 5, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            34 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">「生きるの下手」でお馴染み、せいや大先生が<br>寝ぼけてズボンを前後逆で着てきた時の写真<br>普通そういうのはシャツやろ <a href="https://t.co/6F3H0f2z0T">pic.twitter.com/6F3H0f2z0T</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1087451076737957888?ref_src=twsrc%5Etfw">January 21, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            35 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">M-1グランプリ優勝させて頂きました！<br>14代目ひょうきん者です<br>ありがとうございました</p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1069581613430857728?ref_src=twsrc%5Etfw">December 3, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            36 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">「生きるの下手」でお馴染み、せいや大先生が「服が汚れるロケなので着替えを持参して下さい」と言われてて、案の定汚れたので、いざ着替えようとしたら、服やと思って持って来てた物がよく見ると小さいカバンやって、着れる服が無くなった時の写真 <a href="https://t.co/X7Zq8MBYlP">pic.twitter.com/X7Zq8MBYlP</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1068508318648287234?ref_src=twsrc%5Etfw">November 30, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            37 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">「生きるの下手」でお馴染み、せいや大先生がおにぎりをおかずにご飯を食べていた時の写真 <a href="https://t.co/6ip1WMzao8">pic.twitter.com/6ip1WMzao8</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1068148334383194112?ref_src=twsrc%5Etfw">November 29, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            38 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">よかった <a href="https://t.co/8nzrMve01v">pic.twitter.com/8nzrMve01v</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1063749833289154561?ref_src=twsrc%5Etfw">November 17, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            39 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">今入ったミスドの店員鼻くそほじってましたねぇ〜<br>ムカつきますねぇ〜<br>もう僕ゴールデンチョコレート食べれませんねぇ〜</p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1039475041317019653?ref_src=twsrc%5Etfw">September 11, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            40 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">あいだみつをそんなん言わんねん <a href="https://t.co/12Tjlep8mj">pic.twitter.com/12Tjlep8mj</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1032637545639686144?ref_src=twsrc%5Etfw">August 23, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            41 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">あいだみつをそんなん言わんねん <a href="https://t.co/sYeSTGXCjL">pic.twitter.com/sYeSTGXCjL</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1032284545201070081?ref_src=twsrc%5Etfw">August 22, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            42 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">あいだみつをそんなん言わんねん <a href="https://t.co/w4Q17crrxx">pic.twitter.com/w4Q17crrxx</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1031893933675044865?ref_src=twsrc%5Etfw">August 21, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            43 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">あいだみつをそんなん言わんねん <a href="https://t.co/J0q63eFcVL">pic.twitter.com/J0q63eFcVL</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1031537715190222848?ref_src=twsrc%5Etfw">August 20, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            44 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">中盤に鬼門 <a href="https://t.co/2RHRHhKIKg">pic.twitter.com/2RHRHhKIKg</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1023257014019928065?ref_src=twsrc%5Etfw">July 28, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            45 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">奇跡 <a href="https://t.co/n1S1ollFSw">pic.twitter.com/n1S1ollFSw</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1016304291663904769?ref_src=twsrc%5Etfw">July 9, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            46 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">いやストイックやな <a href="https://t.co/BIGrHzQyo2">pic.twitter.com/BIGrHzQyo2</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1016677275457110016?ref_src=twsrc%5Etfw">July 10, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
            47 => '<blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">ファインディング・ニモツ <a href="https://t.co/TSSv30A32Z">pic.twitter.com/TSSv30A32Z</a></p>&mdash; 粗品（霜降り明星） (@soshina3) <a href="https://twitter.com/soshina3/status/1011966008670633984?ref_src=twsrc%5Etfw">June 27, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
        );

        $numbers = rand(0,47);

        $tweets = $tweets[$numbers];

        \Log::debug($tweets[$numbers]);
        return view('answer')->with([
            "contents" => $contents,
            "tweets" => $tweets,
         ]);
    }
}
